/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/*
 * Class:     com_hero_org_util_SubFolder
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hero_org_util_SubFolder_add(JNIEnv *env, jobject obj, jint x, jint y) {
	return x + y;
}

