/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hero_org_util_BackgroundProcess */

#ifndef _Included_com_hero_org_util_BackgroundProcess
#define _Included_com_hero_org_util_BackgroundProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hero_org_util_BackgroundProcess
 * Method:    checkValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hero_org_util_BackgroundProcess_checkValid(JNIEnv *, jobject);

/*
 * Class:     com_hero_org_util_BackgroundProcess
 * Method:    processData
 * Signature: (Lcom/hero/org/util/BackgroundProcess;)V
 */
JNIEXPORT void JNICALL Java_com_hero_org_util_BackgroundProcess_processData
(JNIEnv *, jobject, jobject);

/*
 * Class:     com_hero_org_util_BackgroundProcess
 * Method:    processGarbage
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hero_org_util_BackgroundProcess_processGarbage
(JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
