/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hero_org_util_Business */

#ifndef _Included_com_hero_org_util_Business
#define _Included_com_hero_org_util_Business
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hero_org_util_Business
 * Method:    getPrice
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_hero_org_util_Business_getPrice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hero_org_util_Business
 * Method:    getOrder
 * Signature: (Ljava/lang/String;I)Lcom/hero/org/models/Order;
 */
JNIEXPORT jobject JNICALL Java_com_hero_org_util_Business_getOrder
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_hero_org_util_Business
 * Method:    getRamdomOrder
 * Signature: ()Lcom/hero/org/models/Order;
 */
JNIEXPORT jobject JNICALL Java_com_hero_org_util_Business_getRamdomOrder
  (JNIEnv *, jobject);

/*
 * Class:     com_hero_org_util_Business
 * Method:    pullOrder
 * Signature: (Lcom/hero/org/models/Order;)I
 */
JNIEXPORT jint JNICALL Java_com_hero_org_util_Business_pullOrder
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hero_org_util_Business
 * Method:    analyzeOrder
 * Signature: (Lcom/hero/org/models/Order;)V
 */
JNIEXPORT void JNICALL Java_com_hero_org_util_Business_analyzeOrder
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
