/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hero_org_JniToJava */

#ifndef _Included_com_hero_org_JniToJava
#define _Included_com_hero_org_JniToJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hero_org_JniToJava
 * Method:    getPerson
 * Signature: ()Lcom/hero/org/models/Person;
 */JNIEXPORT jobject JNICALL Java_com_hero_org_JniToJava_getPerson(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
