/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hero_org_util_NDK */

#ifndef _Included_com_hero_org_util_NDK
#define _Included_com_hero_org_util_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hero_org_util_NDK
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hero_org_util_NDK_getString(JNIEnv *, jobject);

/*
 * Class:     com_hero_org_util_NDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hero_org_util_NDK_add(JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hero_org_util_NDK
 * Method:    push
 * Signature: (Lcom/hero/org/models/Person;)I
 */
JNIEXPORT void JNICALL Java_com_hero_org_util_NDK_push(JNIEnv *, jobject, jobject);
/*
 * Class:     com_hero_org_util_NDK
 * Method:    fetch
 * Signature: ()Lcom/hero/org/models/Person;
 */
JNIEXPORT jobject JNICALL Java_com_hero_org_util_NDK_fetch(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
