/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hero_org_ObjectToC */

#ifndef _Included_com_hero_org_ObjectToC
#define _Included_com_hero_org_ObjectToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hero_org_ObjectToC
 * Method:    doWithObj
 * Signature: (Lcom/hero/org/models/Student;)Lcom/hero/org/models/Student;
 */
JNIEXPORT jobject JNICALL Java_com_hero_org_ObjectToC_doWithObj
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
