/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ObjectToC.h"
#include <string.h>
#include "LogCat.h"
/*
 * Class:     com_hero_org_ObjectToC
 * Method:    doWithObj
 * Signature: (Lcom/hero/org/models/Student;)Lcom/hero/org/models/Student;
 */
jobject Java_com_hero_org_ObjectToC_doWithObj(JNIEnv *env, jobject obj, jobject student) {
	LOGE("%s", "我要看到的调试信息^_^");
	jclass student_cls = env->FindClass("com/hero/org/models/Student");
	if (student_cls == NULL)
		return NULL; //can not find class Studnet
	jmethodID getName = (env)->GetMethodID(student_cls, "getName", "()Ljava/lang/String;");
	LOGE("%s", "getName == NULL");
	if (getName == NULL)
		return NULL;
	jmethodID setName = (env)->GetMethodID(student_cls, "setName", "(Ljava/lang/String;)V");
	if (setName == NULL)
		return NULL;
	jmethodID getNumber = (env)->GetMethodID(student_cls, "getNumber", "()I");
	if (getNumber == NULL)
		return NULL;
	jmethodID setNumber = (env)->GetMethodID(student_cls, "setNumber", "(I)V");
	if (setNumber == NULL)
		return NULL;
	jmethodID printInfo = (env)->GetMethodID(student_cls, "printInfo", "()V");
	jobject mStudent = student;
	LOGE("%s", "mStudent == NULL");
	if (mStudent == NULL)
		return NULL;
	/////////////////////////////////////////////
	jstring jname_str = NULL;
	LOGE("%s", "我要看到的调试信息^_^");
	char* cname_str = NULL;
	jname_str = (_jstring *)env->CallObjectMethod(mStudent, getName);
	cname_str = (char*) env->GetStringUTFChars(jname_str, 0);
	jint jnum = env->CallIntMethod(mStudent, getNumber);
	__android_log_print(ANDROID_LOG_INFO, "-JNI-", "name: %s", cname_str);
	__android_log_print(ANDROID_LOG_INFO, "-JNI-", "number: %d", jnum);
	env->ReleaseStringUTFChars(jname_str, cname_str);
	env->DeleteLocalRef(jname_str);
	/////////////////////////////////////////////
	jstring jname_string = env->NewStringUTF("LiuJun");
	env->CallVoidMethod(mStudent, setName, jname_string);
	env->CallVoidMethod(mStudent, setNumber, 2);
	env->DeleteLocalRef(jname_string);
	////////////////////////////////////////////
	LOGE("%s", "我要看到的调试信息^_^");
	return mStudent;
}

