/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_herozhou_mymodule_app2_MainActivity */

#ifndef _Included_com_herozhou_mymodule_app2_MainActivity
#define _Included_com_herozhou_mymodule_app2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_herozhou_mymodule_app2_MainActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_herozhou_mymodule_app2_MainActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
